function Head=gJsf2111Read(JsfHead)
%Read Head from JsfHead.fName (*.jsf) file for Message Type 2111 (Container Timestamp Message; 0004824_REV_1.20 used). Warning: NOT TESTED.
%function Head=gJsf2111Read(JsfHead), where
%JsfHead - Jsf Header structure;
%Head - Message Header structure.
%Head include the addition fields: HMessageType, HMessageNum.
%Some messages in a JSF file are generated by external entities then passed to the recording system in containers.  These messages are only checked to see if their length matches that 
%specified in the message header, no other validation is performed.  These contained messages are always preceded by a container timestamp message.  This message contains the receipt
%timestamp of the container message.
%Example: Head=gJsf2111Read(JsfHead);

[fId, mes]=fopen(JsfHead.fName,'r');if ~isempty(mes), error(['gJsfRead2111: ' mes]);end;
LHead=(JsfHead.HMessageType==2111);LenHead=sum(LHead);nHead=find(LHead);
%===Begin Head Allocate for Message Type 2111
Head=struct('HMessageType',2111,'HMessageNum',zeros(1,LenHead),...
    'TimeInSeconds',zeros(1,LenHead),'MillisecondsCurrentSecond',zeros(1,LenHead),'Reserved1',zeros(4,LenHead));
%===End Head Allocate for Message Type 2111
df=0;
for m=1:LenHead,
    %===Begin Head Read for Message Type 2111
    fseek(fId,JsfHead.RSeek(nHead(m))-df,'cof');
    Head.HMessageNum(m)=nHead(m);
    Head.TimeInSeconds(m)=fread(fId,1,'int32'); %0-3// Time in seconds (since the start of time based on time() function) (1/1/1970)
    Head.MillisecondsCurrentSecond(m)=fread(fId,1,'int32'); %4-7// Milliseconds in the current second
    Head.Reserved1(:,m)=fread(fId,4,'uint8'); %8-11// Reserved – Do not use
    %===End Head Read for Message Type 2111
    df=ftell(fId);
end;
fclose(fId);

%mail@ge0mlib.com 01/08/2016